services:
  - type: web
    name: heart-disease-predictor
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
    plan: free
    autoDeploy: true
